import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  changelogsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
